[project]
name = "SuperXML"
version = "1.0.0"
description = ""
main_script = "./main.py"

[packages]
PyQt5 = "5.15.7"
QScintilla = "2.13.3"
jedi = "0.18.1"

[scripts]
build-qrc = "pyrcc5 ./icons/resouces.qrc -o ./resources.py"
upgrade-pip = "python -m pip install --upgrade pip"
